spring:
  data:
    redis:
      port: 6379
      host: localhost
      channels:
        follower: follower_channel
        mentorship: mentorship_channel
        achievement: achievement_channel
        event_start: event_start_channel

  mail:
    host: smtp.gmail.com
    port: 587
    username: firstmainserver@gmail.com #https://www.baeldung.com/spring-email
    password: * #https://support.google.com/mail/answer/7104828?hl=en&rd=3&visit_id=638195765566773400-3814427644
    default_subject: "FAANG school"
    sender_email: "noreply@faang-school.com"
    properties:
      mail:
        smtp:
          debug: true
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  messages:
    basename: messages

server:
  port: 8083

logging:
  level:
    root: info

#Можно зарегистрировать аккаунт без привязки карты. Будет 2 евро на отправку тестовых SMS
vonage: #https://dashboard.nexmo.com/getting-started/sms
  api:
    key: 5c2ec2aa
    secret: Xw8jxsmmnUCjQNid
    from: Vonage APIs

project-service:
  host: localhost
  port: 8082
user-service:
  host: localhost
  port: 8080

telegram:
  botUserName: CorpX_bot
  botToken: 6465525589:AAG0RzvhuGF398lj793npi-le8arqZcTxJQ

